---
inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - bin/*
  TargetRubyVersion: 2.4

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
    - ./*.gemspec

Metrics/ModuleLength:
  Exclude:
    - spec/**/*.rb

Style/LambdaCall:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Exclude:
    - apps/**/*.rb
    - spec/**/*.rb

Style/BlockDelimiters:
  Enabled: false
